services:
  - type: web
    name: inhouse-eshop
    env: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
      - key: FRONTEND_URL
        value: https://jinstoremax.netlify.app,https://mybackoffice.netlify.app,https://pratik667.github.io/flights-prices/